### ISSUE TITLE
Arum not recognizing the main function

### ISSUE THREAD

**Issue by ofsho** [ArumLang/Arum#2]
```
use: "std"

main=()=>{
        println("Hello, world!")
}
[[{"type":"use","module":{"type":"string","value":"\"std\"","text":"\"std\"","offset":5,"lineBreaks":0,"line":1,"col":6}},{"type":"var_assign","var_name":{"type":"identifier","value":"main","text":"main","offset":12,"lineBreaks":0,"line":3,"col":1},"var_value":{"type":"lambda","parameters":[],"body":[[]]}}],[{"type":"use","module":{"type":"string","value":"\"std\"","text":"\"std\"","offset":5,"lineBreaks":0,"line":1,"col":6}},{"type":"var_assign","var_name":{"type":"identifier","value":"main","text":"main","offset":12,"lineBreaks":0,"line":3,"col":1},"var_value":{"type":"lambda","parameters":[],"body":[[]]}}]]
undefined
modules/interpreter.js:135
        throw new Error('Unknown statement type: ' + node.type);
              ^

Error: Unknown statement type: undefined
    at generateStatement (interpreter.js:135:15)
    at generate (interpreter.js:65:24)
    at interpreter.js:44:69
    at Generator.next (<anonymous>)
    at interpreter.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (interpreter.js:5:12)
    at main (interpreter.js:28:12)
    at Object.run (interpreter.js:23:5)
    at Object.<anonymous> (cli.js:11:26)
```

I am making a cli, this is its current code:
```typescript
import * as arum from './index';
import * as fs from 'fs';

if (process.argv.length < 3) {
  console.log('Usage: arum <command> <filename>');
  process.exit(1);
}

switch (process.argv[2]) {
    case '-r':
        console.log(arum.run(fs.readFileSync(process.argv[3], 'utf8')));
        break;
    default:
        console.log('Usage: arum <command> <filename>');
        console.log('-----------Commands-------------\n');
        console.log('  -r <filename>\t\tRuns the file');
        break;
}
```

and this is the arum file I am running:
```
use: "std"

main=()=>{
    println("Hello, world!")
}
```

The error is directed at the `main` function which I tried to change multiple times..

**Comment by ofsho** [comment]
Issue also occurs in normal javascript

```typescript
import * as arum from './index';
import * as fs from 'fs';
arum.run("main=()=>{\n\tprintln(\"Hello, world!\")\n}");
```

**Comment by ofsho** [comment]
#5 fits this description

**Comment by ofsho** [comment]
#5 fits this
